spring:
  main:
    web-application-type: servlet
  application:
    name: curious-tunes
  datasource:
    url: jdbc:h2:file:~/ctunes/ctunes-prod;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql.init.mode: always
  jpa.defer-datasource-initialization: false
  title: cTunes
  h2:
    console:
      enabled: true
  cache:
    caffeine:
      spec: "maximumSize=5,expireAfterAccess=600s"

server:
  port: 7777


logging.level.org.jooq.Constants: off

