spring:
  main:
    web-application-type: none
  application:
    name: curious-tunes
  datasource:
    url: jdbc:h2:file:~/ctunes-prod;DB_CLOSE_ON_EXIT=FALSE:application
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql.init.mode: always
  jpa.defer-datasource-initialization: false
  title: cTunes
  h2:
    console:
      enabled: true
